### ISSUE TITLE
possible python version

### ISSUE THREAD

**Issue by falseywinchnet** [tgchomia/ts#2]
import numpy as np
from scipy.spatial.distance import pdist, squareform
import matplotlib.pyplot as plt

# Generate Lorenz attractor data
def lorenz(x, y, z, s=10, r=28, b=2.667):
    x_dot = s*(y - x)
    y_dot = r*x - y - x*z
    z_dot = x*y - b*z
    return x_dot, y_dot, z_dot

dt = 0.01
steps = 10000
xs = np.empty(steps)
ys = np.empty(steps)
zs = np.empty(steps)

# Set initial conditions
xs[0], ys[0], zs[0] = (0., 1., 1.05)

# Generate the attractor
for i in range(steps-1):
    x_dot, y_dot, z_dot = lorenz(xs[i], ys[i], zs[i])
    xs[i + 1] = xs[i] + (x_dot * dt)
    ys[i + 1] = ys[i] + (y_dot * dt)
    zs[i + 1] = zs[i] + (z_dot * dt)

# Use x-component as our time series
data_tot = xs[5000:] # Remove initial transients
x_train = data_tot[:600]
x_test = data_tot[600:700]

# Forecast Horizon
fstH = 100

# Time-series to Distance Matrix
dm = squareform(pdist(x_train.reshape(-1, 1), metric='euclidean'))

# Extract Local Topology
def extract_LT(x):
    pos_weights = np.array([2**0, 2**1, 2**2, 2**7, 0, 2**3, 2**6, 2**5, 2**4])
    new_values = (x >= x[4]).astype(int)
    return np.sum(pos_weights * new_values)

# Pad distance matrix
dm_padded = np.pad(dm, pad_width=1, mode='constant')

# Extract local topology values
LT_Output = np.zeros_like(dm)
for i in range(dm.shape[0]):
    for j in range(dm.shape[1]):
        window = dm_padded[i:i+3, j:j+3]
        LT_Output[i,j] = extract_LT(window.flatten())

# Create Local Topological Layers
LT_layers = LT_Output[1:-1, 1:-1]

# Create the layers with different thresholds
def create_layer(lt_layers, thresh_low, thresh_high=None, value=1):
    layer = np.zeros_like(lt_layers)
    if thresh_high is None:
        layer[lt_layers >= thresh_low] = value
    else:
        mask = (lt_layers >= thresh_low) & (lt_layers < thresh_high)
        layer[mask] = value
    return layer

layer_1 = create_layer(LT_layers, 42.5, value=1)
layer_2 = create_layer(LT_layers, 42.5, 85.5, value=2)
layer_3 = create_layer(LT_layers, 85.5, 127.5, value=3)
layer_4 = create_layer(LT_layers, 127.5, 170.5, value=4)
layer_5 = create_layer(LT_layers, 170.5, 212.5, value=5)
layer_6 = create_layer(LT_layers, 212.5, value=6)

# Flatten layers
flattened_layers = layer_1 + layer_2 + layer_3 + layer_4 + layer_5 + layer_6

# Create 1-D weight vector
prior_states = flattened_layers[:-1]
rv_xm = flattened_layers[-1]

S_im = np.array([np.mean(rv_xm == rv_xi) for rv_xi in prior_states])

# S_im Threshold Maximization
testseqth = np.arange(0.61, 1.01, 0.01)
archetypes = None
max_matches = 0

for thresh in testseqth:
    matches = np.where(S_im > thresh)[0]
    valid_matches = matches[matches < (len(x_train) - fstH - 2)]
    if len(valid_matches) >= 3 and len(valid_matches) > max_matches:
        archetypes = valid_matches
        max_matches = len(valid_matches)

# Generate forecast
arche_data = np.array([x_train[i+3:i+fstH+3] for i in archetypes])
FReT_forecast = np.mean(arche_data, axis=0)

# Plot results
plt.figure(figsize=(10, 6))
plt.plot(x_test, 'b-', label='Test Data', linewidth=2)
plt.plot(FReT_forecast, 'r--', label='FReT', linewidth=2)
plt.legend()
plt.title('FReT Forecast vs Test Data')
plt.show()

**Comment by falseywinchnet** [comment]
discussing this method with claude, i have to ask- does phase space also have a topology?

**Comment by tgchomia** [comment]
Thanks for the question! Yes, with a basis in nonlinear dynamics theory.
